name: Terraform Destroy
on:
 workflow_dispatch:

jobs:
 tf-destroy:
   runs-on: ubuntu-latest
   env:
     GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
   steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Terraform                                                                      
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        id: init
        run: terraform init  
        
      - name: Show Destroy plan
        run: terraform plan -destroy
        continue-on-error: true

      - name: Terraform destroy
        id: destroy
        run: terraform destroy -auto-approve
