name: Terraform Destroy
on:
 workflow_dispatch:

jobs:
 tf-destroy:
   runs-on: ubuntu-latest
   env:
     GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
   steps:
     - name: Terraform destroy
       id: destroy
       run: terraform destroy -auto-approved
